### ISSUE TITLE
Secure Token option

### ISSUE THREAD

**Issue by xantari** [pnmcosta/recaptchav2dotnet#1]
Hi,

I have yet to find any information on how to implement the secure token option with Recaptcha and the .NET api.

Any ideas on how to add that as an option?

https://developers.google.com/recaptcha/docs/secure_token

Here is some discussion on how to do the encryption for the secure token:

http://stackoverflow.com/questions/31478724/how-to-generate-a-google-recaptcha-v2-secure-token-with-php

FYI, the secure token option is useful for sites where you have multiple domains and only want to manage one secret key.

**Comment by pnmcosta** [comment]
Hi,

That is definitely an option, would you like to contribute?

Looking at the Java example for the secure token, see https://github.com/google/recaptcha-java/blob/master/appengine/src/main/java/com/google/recaptcha/STokenUtils.java

sessionid looks to be a random guid, and ts_ms the current time in miliseconds.

whats crucial is that this is in a Json format and is then encrypted using the site_key provided.

Cheers,
P.

**Comment by xantari** [comment]
I was able to implement this after several hours of experimentation. Googles recaptcha 2.0 requires very specific encryption requirements and hashing of the secret key for them to verify the secure token. You can take a look at my working implementation here which is based off of their Java published example:

https://github.com/xantari/RecaptchaV2.NET

**Comment by pnmcosta** [comment]
Nicely done mate, well done :+1:
